// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjl5OncIfCfw6p8YE8f9Ha250QwuWSvFE',
    appId: '1:884021462297:web:b13c894a3eea3be2a63188',
    messagingSenderId: '884021462297',
    projectId: 'weather-app-a47e9',
    authDomain: 'weather-app-a47e9.firebaseapp.com',
    storageBucket: 'weather-app-a47e9.firebasestorage.app',
    measurementId: 'G-S4CTY07039',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QGd59EDN-9jUJMhHS5CRJQ09qpSgPlA',
    appId: '1:884021462297:android:6c2c7fe5b113376fa63188',
    messagingSenderId: '884021462297',
    projectId: 'weather-app-a47e9',
    storageBucket: 'weather-app-a47e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyIgXYcPGf2Fk5ijMiP0KGcSDpNy06efM',
    appId: '1:884021462297:ios:38ff43c08aa87408a63188',
    messagingSenderId: '884021462297',
    projectId: 'weather-app-a47e9',
    storageBucket: 'weather-app-a47e9.firebasestorage.app',
    iosBundleId: 'com.example.weatherrapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyIgXYcPGf2Fk5ijMiP0KGcSDpNy06efM',
    appId: '1:884021462297:ios:38ff43c08aa87408a63188',
    messagingSenderId: '884021462297',
    projectId: 'weather-app-a47e9',
    storageBucket: 'weather-app-a47e9.firebasestorage.app',
    iosBundleId: 'com.example.weatherrapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjl5OncIfCfw6p8YE8f9Ha250QwuWSvFE',
    appId: '1:884021462297:web:d165842577916f36a63188',
    messagingSenderId: '884021462297',
    projectId: 'weather-app-a47e9',
    authDomain: 'weather-app-a47e9.firebaseapp.com',
    storageBucket: 'weather-app-a47e9.firebasestorage.app',
    measurementId: 'G-6PH4DT1BTW',
  );
}
